### ISSUE TITLE
Add Synology CSI

### ISSUE THREAD

**Issue by jlor** [x00-sh/home-ops#6]

**Comment by jlor** [comment]
Solved.
See commits:
72a5da2eb64b8043755e3cf7b29fc88dc53f6822
c086e08a74a85d4c27242834cc88a71afac99abf


`[synology-csi-client-info](https://github.com/x00-sh/home-ops/blob/c086e08a74a85d4c27242834cc88a71afac99abf/kubernetes/apps/storage/synology-csi/app/secret.sops.yaml)` contents:
```yaml
apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-client-info
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: |
        clients:
        - host: <server>
          port: <port>
          https: false
          username: <username>
          password: <password>

```
